# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1024, 720)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1024, 720))
        MainWindow.setMaximumSize(QtCore.QSize(1024, 720))
        MainWindow.setStyleSheet("background-color: rgb(245, 160, 152)")
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMaximumSize(QtCore.QSize(1024, 720))
        self.centralwidget.setStyleSheet(".QWidget{background-image: url(\"C:/MyFolder/MyWorks/university/IUS_Uhimec_Karmanova/Kyrsach/programm/prog/Manager/res/main_backend.jpg\")}")
        self.centralwidget.setObjectName("centralwidget")
        self.bt_exit = QtWidgets.QPushButton(self.centralwidget)
        self.bt_exit.setGeometry(QtCore.QRect(910, 660, 100, 50))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium Cond")
        font.setPointSize(14)
        self.bt_exit.setFont(font)
        self.bt_exit.setStyleSheet("QPushButton {\n"
"    background-color:rgb(41, 3, 79);\n"
"    border: 2px solid rgb(255, 90, 129);\n"
"    border-radius: 20px;\n"
"    color: white;\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color:rgb(22, 1, 43);\n"
"}")
        self.bt_exit.setCheckable(False)
        self.bt_exit.setAutoRepeat(False)
        self.bt_exit.setAutoExclusive(False)
        self.bt_exit.setObjectName("bt_exit")
        self.bt_start = QtWidgets.QPushButton(self.centralwidget)
        self.bt_start.setEnabled(True)
        self.bt_start.setGeometry(QtCore.QRect(120, 140, 180, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_start.sizePolicy().hasHeightForWidth())
        self.bt_start.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium Cond")
        font.setPointSize(14)
        font.setItalic(False)
        self.bt_start.setFont(font)
        self.bt_start.setStyleSheet("QPushButton {\n"
"    background-color:rgb(41, 3, 79);\n"
"    border: 2px solid rgb(255, 90, 129);\n"
"    border-radius: 20px;\n"
"    color: white;\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color:rgb(22, 1, 43);\n"
"}")
        self.bt_start.setObjectName("bt_start")
        self.bt_connect = QtWidgets.QPushButton(self.centralwidget)
        self.bt_connect.setEnabled(True)
        self.bt_connect.setGeometry(QtCore.QRect(20, 60, 180, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_connect.sizePolicy().hasHeightForWidth())
        self.bt_connect.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium Cond")
        font.setPointSize(14)
        font.setItalic(False)
        self.bt_connect.setFont(font)
        self.bt_connect.setStyleSheet("QPushButton {\n"
"    background-color:rgb(41, 3, 79);\n"
"    border: 2px solid rgb(255, 90, 129);\n"
"    border-radius: 20px;\n"
"    color: white;\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color:rgb(22, 1, 43);\n"
"}")
        self.bt_connect.setObjectName("bt_connect")
        self.label_connect = QtWidgets.QLabel(self.centralwidget)
        self.label_connect.setGeometry(QtCore.QRect(20, 20, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_connect.setFont(font)
        self.label_connect.setStyleSheet("color: rgb(41, 3, 79);\n"
"background-color: rgb(255, 90, 129);\n"
"border-radius: 10px;\n"
"    \n"
"")
        self.label_connect.setObjectName("label_connect")
        self.bt_mission = QtWidgets.QPushButton(self.centralwidget)
        self.bt_mission.setEnabled(True)
        self.bt_mission.setGeometry(QtCore.QRect(230, 60, 180, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_mission.sizePolicy().hasHeightForWidth())
        self.bt_mission.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium Cond")
        font.setPointSize(14)
        font.setItalic(False)
        self.bt_mission.setFont(font)
        self.bt_mission.setStyleSheet("QPushButton {\n"
"    background-color:rgb(41, 3, 79);\n"
"    border: 2px solid rgb(255, 90, 129);\n"
"    border-radius: 20px;\n"
"    color: white;\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color:rgb(22, 1, 43);\n"
"}")
        self.bt_mission.setObjectName("bt_mission")
        self.label_mission = QtWidgets.QLabel(self.centralwidget)
        self.label_mission.setGeometry(QtCore.QRect(230, 20, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_mission.setFont(font)
        self.label_mission.setStyleSheet("color: rgb(41, 3, 79);\n"
"background-color: rgb(255, 90, 129);\n"
"border-radius: 10px;")
        self.label_mission.setObjectName("label_mission")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 520, 391, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: none;\n"
"color: white;")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 590, 381, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: none;\n"
"color: white;")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(120, 640, 161, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color: none;\n"
"color: white;")
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.bt_exit.clicked.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.bt_exit.setText(_translate("MainWindow", "Exit"))
        self.bt_start.setText(_translate("MainWindow", "Start  simulation"))
        self.bt_connect.setText(_translate("MainWindow", "Connect"))
        self.label_connect.setText(_translate("MainWindow", "fail"))
        self.bt_mission.setText(_translate("MainWindow", "Set a mission"))
        self.label_mission.setText(_translate("MainWindow", "No mission"))
        self.label.setText(_translate("MainWindow", "\n"
"object search program using an"))
        self.label_2.setText(_translate("MainWindow", " underwater unmanned vehicle"))
        self.label_3.setText(_translate("MainWindow", "WHALE V1.0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
