# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'set_mission_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SetMissionWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1011, 620)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1011, 620))
        MainWindow.setMaximumSize(QtCore.QSize(1011, 636))
        MainWindow.setStyleSheet("background-color: rgb(245, 160, 152);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.list_points = QtWidgets.QListWidget(self.centralwidget)
        self.list_points.setMinimumSize(QtCore.QSize(400, 0))
        self.list_points.setMaximumSize(QtCore.QSize(400, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.list_points.setFont(font)
        self.list_points.setStyleSheet("background-color: rgb(255, 90, 129);")
        self.list_points.setObjectName("list_points")
        self.gridLayout.addWidget(self.list_points, 0, 2, 1, 1)
        self.holst = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.holst.sizePolicy().hasHeightForWidth())
        self.holst.setSizePolicy(sizePolicy)
        self.holst.setMinimumSize(QtCore.QSize(500, 500))
        self.holst.setMaximumSize(QtCore.QSize(500, 500))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.holst.setFont(font)
        self.holst.setStyleSheet("background-color: white;")
        self.holst.setObjectName("holst")
        self.gridLayout.addWidget(self.holst, 0, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.spin_x_min = QtWidgets.QDoubleSpinBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.spin_x_min.setFont(font)
        self.spin_x_min.setDecimals(0)
        self.spin_x_min.setMinimum(-9999.0)
        self.spin_x_min.setMaximum(-1.0)
        self.spin_x_min.setSingleStep(10.0)
        self.spin_x_min.setProperty("value", -100.0)
        self.spin_x_min.setObjectName("spin_x_min")
        self.horizontalLayout.addWidget(self.spin_x_min)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.spin_x_max = QtWidgets.QDoubleSpinBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.spin_x_max.setFont(font)
        self.spin_x_max.setDecimals(0)
        self.spin_x_max.setMinimum(1.0)
        self.spin_x_max.setMaximum(9999.0)
        self.spin_x_max.setSingleStep(10.0)
        self.spin_x_max.setProperty("value", 100.0)
        self.spin_x_max.setObjectName("spin_x_max")
        self.horizontalLayout.addWidget(self.spin_x_max)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 1, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.spin_y_max = QtWidgets.QDoubleSpinBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.spin_y_max.setFont(font)
        self.spin_y_max.setDecimals(0)
        self.spin_y_max.setMinimum(1.0)
        self.spin_y_max.setMaximum(9999.0)
        self.spin_y_max.setSingleStep(10.0)
        self.spin_y_max.setProperty("value", 100.0)
        self.spin_y_max.setObjectName("spin_y_max")
        self.verticalLayout.addWidget(self.spin_y_max)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.spin_y_min = QtWidgets.QDoubleSpinBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.spin_y_min.setFont(font)
        self.spin_y_min.setReadOnly(False)
        self.spin_y_min.setDecimals(0)
        self.spin_y_min.setMinimum(-9999.0)
        self.spin_y_min.setMaximum(-1.0)
        self.spin_y_min.setSingleStep(10.0)
        self.spin_y_min.setProperty("value", -100.0)
        self.spin_y_min.setObjectName("spin_y_min")
        self.verticalLayout.addWidget(self.spin_y_min)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.bt_add = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(50)
        sizePolicy.setHeightForWidth(self.bt_add.sizePolicy().hasHeightForWidth())
        self.bt_add.setSizePolicy(sizePolicy)
        self.bt_add.setMinimumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium Cond")
        font.setPointSize(14)
        self.bt_add.setFont(font)
        self.bt_add.setStyleSheet("QPushButton {\n"
"    background-color:rgb(41, 3, 79);\n"
"    border: 2px solid rgb(255, 90, 129);\n"
"    border-radius: 20px;\n"
"    color: white;\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color:rgb(22, 1, 43);\n"
"}")
        self.bt_add.setCheckable(False)
        self.bt_add.setAutoRepeat(False)
        self.bt_add.setAutoExclusive(False)
        self.bt_add.setObjectName("bt_add")
        self.horizontalLayout_2.addWidget(self.bt_add)
        self.bt_remove = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(50)
        sizePolicy.setHeightForWidth(self.bt_remove.sizePolicy().hasHeightForWidth())
        self.bt_remove.setSizePolicy(sizePolicy)
        self.bt_remove.setMinimumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium Cond")
        font.setPointSize(14)
        self.bt_remove.setFont(font)
        self.bt_remove.setStyleSheet("QPushButton {\n"
"    background-color:rgb(41, 3, 79);\n"
"    border: 2px solid rgb(255, 90, 129);\n"
"    border-radius: 20px;\n"
"    color: white;\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color:rgb(22, 1, 43);\n"
"}")
        self.bt_remove.setCheckable(False)
        self.bt_remove.setAutoRepeat(False)
        self.bt_remove.setAutoExclusive(False)
        self.bt_remove.setObjectName("bt_remove")
        self.horizontalLayout_2.addWidget(self.bt_remove)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.bt_scan = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(50)
        sizePolicy.setHeightForWidth(self.bt_scan.sizePolicy().hasHeightForWidth())
        self.bt_scan.setSizePolicy(sizePolicy)
        self.bt_scan.setMinimumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium Cond")
        font.setPointSize(14)
        self.bt_scan.setFont(font)
        self.bt_scan.setStyleSheet("QPushButton {\n"
"    background-color:rgb(41, 3, 79);\n"
"    border: 2px solid rgb(255, 90, 129);\n"
"    border-radius: 20px;\n"
"    color: white;\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color:rgb(22, 1, 43);\n"
"}")
        self.bt_scan.setCheckable(False)
        self.bt_scan.setAutoRepeat(False)
        self.bt_scan.setAutoExclusive(False)
        self.bt_scan.setObjectName("bt_scan")
        self.horizontalLayout_2.addWidget(self.bt_scan)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.bt_save = QtWidgets.QPushButton(self.centralwidget)
        self.bt_save.setMinimumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium Cond")
        font.setPointSize(14)
        font.setItalic(False)
        self.bt_save.setFont(font)
        self.bt_save.setStyleSheet("QPushButton {\n"
"    background-color:rgb(41, 3, 79);\n"
"    border: 2px solid rgb(255, 90, 129);\n"
"    border-radius: 20px;\n"
"    color: white;\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color:rgb(22, 1, 43);\n"
"}")
        self.bt_save.setObjectName("bt_save")
        self.horizontalLayout_8.addWidget(self.bt_save)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem3)
        self.bt_cancel = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(50)
        sizePolicy.setHeightForWidth(self.bt_cancel.sizePolicy().hasHeightForWidth())
        self.bt_cancel.setSizePolicy(sizePolicy)
        self.bt_cancel.setMinimumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium Cond")
        font.setPointSize(14)
        self.bt_cancel.setFont(font)
        self.bt_cancel.setStyleSheet("QPushButton {\n"
"    background-color:rgb(41, 3, 79);\n"
"    border: 2px solid rgb(255, 90, 129);\n"
"    border-radius: 20px;\n"
"    color: white;\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color:rgb(22, 1, 43);\n"
"}")
        self.bt_cancel.setCheckable(False)
        self.bt_cancel.setAutoRepeat(False)
        self.bt_cancel.setAutoExclusive(False)
        self.bt_cancel.setObjectName("bt_cancel")
        self.horizontalLayout_8.addWidget(self.bt_cancel)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.bt_remove.clicked.connect(self.list_points.clear)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.bt_add.setText(_translate("MainWindow", "add"))
        self.bt_remove.setText(_translate("MainWindow", "remove"))
        self.bt_scan.setText(_translate("MainWindow", "scan"))
        self.bt_save.setText(_translate("MainWindow", "Save"))
        self.bt_cancel.setText(_translate("MainWindow", "cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
